[package]
name = "commander"
version = "0.1.0"
authors = ["uwe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.10.3"
glib-sys = "0.10.0"
gtk = "0.9.2"
gtk-sys = "0.10"
gio = "0.9.1"
gio-sys = "0.10"
webkit2gtk = "0.11.0"
webkit2gtk-sys = "0.13.0"
tokio = { version = "1.5.0", features = ["full"] }
warp = "0.3.1"
dirs = "3.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
lexical-sort = "0.3"

[features]
default = ["gtk/v3_22", "webkit2gtk/v2_6"]